[package]
name = "sublime-bench"
version = "0.0.0"
edition = "2024"
publish = false

[dependencies]
sublime = { path = ".." }
csv = "1"
serde = "1"
serde_json = "1"
pulldown-cmark = { version = "0.13", features = ["serde"] }
pulldown-cmark-to-cmark = "22"
docx-rs = "0.4"
htmd = "0.2"
html2text = "0.12"
toml = "1"
serde_yaml = "0.9"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = 3
