#!/usr/bin/env python3
"""Writes src/io/rtf/codepage.rs: the upper halves (0x80-0xFF) of the
single-byte code pages RTF names with \\ansicpg and \\fcharset, from
Python's own codecs. Bytes a code page leaves undefined map to U+FFFD.

Run from the repository root: python3 scripts/gen-rtf-codepages.py
"""

PAGES = [
    (437, "cp437"),
    (850, "cp850"),
    (874, "cp874"),
    (1250, "cp1250"),
    (1251, "cp1251"),
    (1252, "cp1252"),
    (1253, "cp1253"),
    (1254, "cp1254"),
    (1255, "cp1255"),
    (1256, "cp1256"),
    (1257, "cp1257"),
    (1258, "cp1258"),
    (10000, "mac_roman"),
]


def upper_half(codec):
    out = []
    for byte in range(0x80, 0x100):
        try:
            text = bytes([byte]).decode(codec)
        except UnicodeDecodeError:
            text = "�"
        out.append(ord(text) if len(text) == 1 else 0xFFFD)
    return out


def main():
    lines = [
        "//! Upper halves (0x80-0xFF) of the single-byte code pages RTF names.",
        "//! Generated by `scripts/gen-rtf-codepages.py`; do not edit.",
        "",
        "/// The characters bytes 0x80-0xFF stand for in `code_page`, when it is",
        "/// one of the single-byte pages kept here.",
        "pub fn upper_half(code_page: u16) -> Option<&'static [u16; 128]> {",
        "    match code_page {",
    ]
    for number, _ in PAGES:
        lines.append(f"        {number} => Some(&CP{number}),")
    lines += ["        _ => None,", "    }", "}", ""]
    for number, codec in PAGES:
        values = upper_half(codec)
        lines.append(f"static CP{number}: [u16; 128] = [")
        for row in range(0, 128, 12):
            chunk = ", ".join(f"0x{value:04X}" for value in values[row : row + 12])
            lines.append(f"    {chunk},")
        lines.append("];")
        lines.append("")
    with open("src/io/rtf/codepage.rs", "w") as handle:
        handle.write("\n".join(lines))


if __name__ == "__main__":
    main()
