"""Writes src/io/pdf/tables.rs: the PDF standard encodings, the glyph
names they and the core fonts use, and the core fonts' widths.

Source: pypdf's copies of Adobe's tables (the encodings of PDF 32000
Annex D, the Adobe Glyph List, and the Core 14 AFM widths). Run from
the repository root: python3 scripts/gen-pdf-tables.py
"""

from pypdf._codecs import (
    _mac_encoding,
    _std_encoding,
    _symbol_encoding,
    _win_encoding,
    _zapfding_encoding,
    adobe_glyphs,
)
from pypdf._codecs.core_font_metrics import CORE_FONT_METRICS

LIGATURES = {"ff": "ff", "fi": "fi", "fl": "fl", "ffi": "ffi", "ffl": "ffl"}


def encoding(name, table):
    codes = [ord(char) if char else 0 for char in table]
    assert len(codes) == 256 and all(code < 0x10000 for code in codes)
    rows = ",\n    ".join(", ".join(str(code) for code in codes[at:at + 16]) for at in range(0, 256, 16))
    return f"pub static {name}: [u16; 256] = [\n    {rows},\n];\n"


def widths(name, metrics):
    pairs = sorted(
        (ord(char), width)
        for char, width in metrics.character_widths.items()
        if char != "default" and len(char) == 1 and ord(char) < 0x10000
    )
    default = metrics.character_widths.get("default", 500)
    body = ", ".join(f"({code}, {width})" for code, width in pairs)
    return (
        f"pub static {name}: Widths = Widths {{\n    default: {default},\n"
        f"    pairs: &[{body}],\n}};\n"
    )


def main():
    chars = set()
    for table in (_std_encoding, _win_encoding, _mac_encoding, _symbol_encoding, _zapfding_encoding):
        chars |= {char for char in table if char}
    for metrics in CORE_FONT_METRICS.values():
        chars |= {char for char in metrics.character_widths if char != "default"}
    names = {
        name[1:]: value
        for name, value in adobe_glyphs.items()
        if len(value) == 1 and value in chars and ord(value) < 0x10000
    }
    ordered = sorted(names)
    joined = "".join(ordered)
    assert len(joined) < 0x10000
    ends = []
    total = 0
    for name in ordered:
        total += len(name)
        ends.append(total)
    out = [
        "//! Generated by scripts/gen-pdf-tables.py from pypdf's copies of Adobe's",
        "//! tables (PDF 32000 Annex D encodings, the Adobe Glyph List, the Core 14",
        "//! AFM widths). Do not edit by hand.",
        "",
        "/// A core font's advance widths (thousandths of an em) by Unicode.",
        "pub struct Widths {",
        "    pub default: u16,",
        "    /// Sorted by code point.",
        "    pub pairs: &'static [(u16, u16)],",
        "}",
        "",
        encoding("STANDARD", _std_encoding),
        encoding("WIN_ANSI", _win_encoding),
        encoding("MAC_ROMAN", _mac_encoding),
        encoding("SYMBOL", _symbol_encoding),
        encoding("ZAPF_DINGBATS", _zapfding_encoding),
        "/// Glyph names in sorted order, run together; `GLYPH_ENDS[i]` is where",
        "/// name i ends and `GLYPH_CODES[i]` its code point.",
        f"pub static GLYPH_NAMES: &str = {joined!r};".replace("'", '"'),
        f"pub static GLYPH_ENDS: [u16; {len(ends)}] = [{', '.join(map(str, ends))}];",
        f"pub static GLYPH_CODES: [u16; {len(ordered)}] = [{', '.join(str(ord(names[name])) for name in ordered)}];",
        "",
        "/// Ligature glyph names, spelled out as the letters they join.",
        "pub static LIGATURES: [(&str, &str); 5] = ["
        + ", ".join(f'("{name}", "{text}")' for name, text in LIGATURES.items())
        + "];",
        "",
    ]
    for rust, font in [
        ("HELVETICA", "Helvetica"),
        ("HELVETICA_BOLD", "Helvetica-Bold"),
        ("TIMES_ROMAN", "Times-Roman"),
        ("TIMES_BOLD", "Times-Bold"),
        ("TIMES_ITALIC", "Times-Italic"),
        ("TIMES_BOLD_ITALIC", "Times-BoldItalic"),
        ("SYMBOL_WIDTHS", "Symbol"),
        ("ZAPF_DINGBATS_WIDTHS", "ZapfDingbats"),
    ]:
        out.append(widths(rust, CORE_FONT_METRICS[font]))
    with open("src/io/pdf/tables.rs", "w") as handle:
        handle.write("\n".join(out))


main()
