//! `sublime paths`: every reachable pair, its path, and fidelity.
//! `--markdown` produces DOCS/FORMATS.md exactly.

use std::io::Write;

use crate::cli::args::LogFormat;
use crate::cli::render::json_lines::write_hop;
use crate::cli::{CliError, ExitCode};
use crate::converter::{Converter, FidelityKind};
use crate::converters::image;
use crate::format::{Category, Format};
use crate::io::json::JsonWriter;
use crate::planner::{self, Plan, PlanOptions};
use crate::registry;

pub fn run(
    markdown: bool,
    log_format: LogFormat,
    stdout: &mut dyn Write,
) -> Result<ExitCode, CliError> {
    let text = if markdown {
        render_markdown()
    } else {
        match log_format {
            LogFormat::Human => render_human(),
            LogFormat::Json => render_json(),
        }
    };
    stdout
        .write_all(text.as_bytes())
        .map_err(|error| CliError::Io {
            action: "writing stdout".to_string(),
            error,
        })?;
    Ok(ExitCode::Success)
}

/// Every ordered pair of distinct formats that has a path, in id order.
fn all_plans() -> Vec<Plan> {
    let formats = registry::all_formats();
    let converters = registry::all_converters();
    let options = PlanOptions::default();
    let mut plans = Vec::new();
    for from in &formats {
        for to in &formats {
            if from.id == to.id {
                continue;
            }
            if let Ok(plan) = planner::plan(converters, from, to, &options) {
                plans.push(plan);
            }
        }
    }
    plans
}

fn path_names(plan: &Plan) -> String {
    let names: Vec<&str> = plan.hops.iter().map(|hop| hop.name()).collect();
    names.join(" -> ")
}

fn render_human() -> String {
    let mut text = String::new();
    for plan in all_plans() {
        let line = format!(
            "{} -> {}: {} via {}\n",
            plan.from().id,
            plan.to().id,
            plan.worst_fidelity().label(),
            path_names(&plan)
        );
        text.push_str(&line);
    }
    text
}

fn render_json() -> String {
    let mut buffer: Vec<u8> = Vec::new();
    {
        let mut writer = JsonWriter::new(&mut buffer);
        let _ = writer.begin_array();
        for plan in all_plans() {
            let _ = writer.begin_object();
            let _ = writer.key("from");
            let _ = writer.string(plan.from().id);
            let _ = writer.key("to");
            let _ = writer.string(plan.to().id);
            let _ = writer.key("fidelity");
            let _ = writer.string(plan.worst_fidelity().label());
            let _ = writer.key("hops");
            let _ = writer.begin_array();
            for hop in plan.describe() {
                let _ = write_hop(&mut writer, &hop);
            }
            let _ = writer.end_array();
            let _ = writer.end_object();
        }
        let _ = writer.end_array();
        let _ = writer.flush();
    }
    let mut text = String::from_utf8(buffer).unwrap_or_default();
    text.push('\n');
    text
}

pub fn render_markdown() -> String {
    let mut text = String::new();
    text.push_str("# Formats and Conversion Paths\n\n");
    text.push_str("Generated by `sublime paths --markdown`. Do not edit by hand. CI fails if this file is stale.\n\n");

    text.push_str("## Formats\n\n");
    text.push_str("| Category | Id | Name | Extensions | Produced by | Consumed by |\n");
    text.push_str("|---|---|---|---|---|---|\n");
    let mut formats = registry::all_formats();
    formats.sort_by(|left, right| (left.category, left.id).cmp(&(right.category, right.id)));
    for format in formats {
        let mut produced_by: Vec<&str> = Vec::new();
        let mut consumed_by: Vec<&str> = Vec::new();
        for converter in registry::all_converters() {
            if converter.to().id == format.id {
                produced_by.push(converter.name());
            }
            if converter.from().id == format.id {
                consumed_by.push(converter.name());
            }
        }
        let line = format!(
            "| {} | {} | {} | {} | {} | {} |\n",
            format.category.label(),
            format.id,
            format.display_name,
            format.extensions.join(", "),
            or_dash(&produced_by),
            or_dash(&consumed_by)
        );
        text.push_str(&line);
    }

    text.push_str("\n## Converters\n\n");
    text.push_str("| Name | From | To | Tier | Fidelity | Notes |\n");
    text.push_str("|---|---|---|---|---|---|\n");
    for converter in registry::all_converters() {
        let fidelity = converter.fidelity();
        let line = format!(
            "| {} | {} | {} | {} | {} | {} |\n",
            converter.name(),
            converter.from().id,
            converter.to().id,
            converter.tier().label(),
            fidelity.kind().label(),
            fidelity.description().unwrap_or("")
        );
        text.push_str(&line);
    }

    text.push_str("\n## Paths\n\n");
    text.push_str("| From | To | Fidelity | Path | Notes |\n");
    text.push_str("|---|---|---|---|---|\n");
    for plan in all_plans() {
        let notes = plan.loss_descriptions().join("; ");
        let line = format!(
            "| {} | {} | {} | {} | {} |\n",
            plan.from().id,
            plan.to().id,
            plan.worst_fidelity().label(),
            path_names(&plan),
            notes
        );
        text.push_str(&line);
    }

    text.push_str("\n## Map\n\n");
    text.push_str("One graph per category and one for the crossings between them. A line joins two formats with a converter between them, in either direction; the image category joins every format to its pixel hub instead, since every image converts through it. The grid under each graph gives every pair (rows from, columns to): ● lossless, ■ conditional, ▲ lossy, with the number of hops (1 is a direct converter), blank for no path. The Paths table above has each path and what it loses.\n\n");
    text.push_str(&render_mermaid());
    text
}

/// The map at the bottom of DOCS/FORMATS.md: one Mermaid graph per
/// category and a last graph of the converters that cross categories.
/// A graph shows only which formats convert directly: one plain line
/// per pair with a converter either way. The image category, whose
/// pairs are all generated through its pixel hub, draws the hub with a
/// line to each format instead of every pair. What a conversion loses
/// and how many hops it takes are in the grid under each graph.
#[inline(never)]
fn render_mermaid() -> String {
    let mut formats = registry::all_formats();
    formats.sort_by(|left, right| (left.category, left.id).cmp(&(right.category, right.id)));
    let converters = registry::all_converters();
    let plans = all_plans();
    let mut text = String::new();
    let mut categories: Vec<Category> = formats.iter().map(|format| format.category).collect();
    categories.dedup();
    for category in &categories {
        text.push_str("### ");
        text.push_str(category.label());
        text.push_str("\n\n```mermaid\ngraph LR\n");
        let mut lines: Vec<(String, String)> = Vec::new();
        if *category == Category::Image {
            // Every other format on the hub's left, so the spokes split
            // over two short columns rather than one long one.
            let spokes = image::codecs().filter(|(format, _, _)| format.category == *category);
            for (index, (format, _, _)) in spokes.enumerate() {
                if index % 2 == 0 {
                    add_line(&mut lines, format.id, HUB);
                } else {
                    add_line(&mut lines, HUB, format.id);
                }
            }
            text.push_str(&format!("  {HUB}{{{{\"{HUB} hub\"}}}}\n"));
        }
        for converter in converters {
            let inside =
                converter.from().category == *category && converter.to().category == *category;
            if inside && !through_hub(*converter) {
                add_line(&mut lines, converter.from().id, converter.to().id);
            }
        }
        push_lines(&mut text, &lines);
        text.push_str("```\n\n");
        push_matrix(&mut text, &formats, *category, &plans);
    }
    // Across categories: the other side drawn as its category.
    let mut crossing: Vec<(String, String)> = Vec::new();
    for converter in converters {
        let from = converter.from();
        let to = converter.to();
        if from.category == to.category {
            continue;
        }
        let (format, other) = if from.category < to.category {
            (from, to.category)
        } else {
            (to, from.category)
        };
        let hub = format!("{}{{{{{}}}}}", other.label(), other.label());
        add_line(&mut crossing, format.id, &hub);
    }
    if !crossing.is_empty() {
        text.push_str("### Between categories\n\n");
        text.push_str("A format's converter into another category opens every path that category already has, so the other side is drawn as the category itself.\n\n```mermaid\ngraph LR\n");
        push_lines(&mut text, &crossing);
        text.push_str("```\n");
    }
    text
}

/// The hub node of the image category: decoded pixels.
const HUB: &str = "pixels";

/// Whether a converter is one of the pairs generated through the hub.
fn through_hub(converter: &dyn Converter) -> bool {
    image::pairs()
        .iter()
        .any(|pair| pair.name == converter.name())
}

/// Adds a line between two nodes unless one is there either way.
fn add_line(lines: &mut Vec<(String, String)>, one: &str, other: &str) {
    let seen = lines
        .iter()
        .any(|(a, b)| (a == one && b == other) || (a == other && b == one));
    if !seen {
        lines.push((one.to_string(), other.to_string()));
    }
}

fn push_lines(text: &mut String, lines: &[(String, String)]) {
    // A hyphenated id is drawn under its own name, not its node id.
    let mut labeled: Vec<&str> = Vec::new();
    for (one, other) in lines {
        for id in [one.as_str(), other.as_str()] {
            if id.contains('-') && !id.contains('{') && !labeled.contains(&id) {
                text.push_str("  ");
                push_mermaid_id(text, id);
                text.push_str(&format!("[\"{id}\"]\n"));
                labeled.push(id);
            }
        }
    }
    for (one, other) in lines {
        text.push_str("  ");
        push_mermaid_id(text, one);
        text.push_str(" --- ");
        push_mermaid_id(text, other);
        text.push('\n');
    }
}

/// The grid's shape for a fidelity.
fn kind_mark(kind: FidelityKind) -> &'static str {
    match kind {
        FidelityKind::Lossless => "●",
        FidelityKind::Conditional => "■",
        FidelityKind::Lossy => "▲",
    }
}

/// A from-by-to grid of a category's formats: each cell the worst
/// fidelity of the path between them and its number of hops.
fn push_matrix(text: &mut String, formats: &[&Format], category: Category, plans: &[Plan]) {
    let members: Vec<&str> = formats
        .iter()
        .filter(|format| format.category == category)
        .map(|format| format.id)
        .collect();
    text.push_str("| from \\ to |");
    for id in &members {
        text.push(' ');
        text.push_str(id);
        text.push_str(" |");
    }
    text.push_str("\n|---|");
    for _ in &members {
        text.push_str(":-:|");
    }
    text.push('\n');
    for from in &members {
        text.push_str("| **");
        text.push_str(from);
        text.push_str("** |");
        for to in &members {
            let cell = if from == to {
                "·".to_string()
            } else {
                plans
                    .iter()
                    .find(|plan| plan.from().id == *from && plan.to().id == *to)
                    .map_or(String::new(), |plan| {
                        format!("{} {}", kind_mark(plan.worst_fidelity()), plan.hops.len())
                    })
            };
            text.push(' ');
            text.push_str(&cell);
            text.push_str(" |");
        }
        text.push('\n');
    }
    text.push('\n');
}

/// Mermaid node ids cannot contain hyphens, which read as edge syntax.
/// A shape (`name{{label}}`) passes through as it is.
fn push_mermaid_id(text: &mut String, format_id: &str) {
    if format_id.contains('{') {
        text.push_str(format_id);
        return;
    }
    for ch in format_id.chars() {
        if ch == '-' {
            text.push('_');
        } else {
            text.push(ch);
        }
    }
}

fn or_dash(names: &[&str]) -> String {
    if names.is_empty() {
        return "-".to_string();
    }
    names.join(", ")
}
