//! `sublime paths`: every reachable pair, its path, and fidelity.
//! `--markdown` produces DOCS/FORMATS.md exactly.

use std::io::Write;

use crate::cli::args::LogFormat;
use crate::cli::render::json_lines::write_hop;
use crate::cli::{CliError, ExitCode};
use crate::converter::{Converter, FidelityKind};
use crate::format::Category;
use crate::io::json::JsonWriter;
use crate::planner::{self, Plan, PlanOptions};
use crate::registry;

pub fn run(
    markdown: bool,
    log_format: LogFormat,
    stdout: &mut dyn Write,
) -> Result<ExitCode, CliError> {
    let text = if markdown {
        render_markdown()
    } else {
        match log_format {
            LogFormat::Human => render_human(),
            LogFormat::Json => render_json(),
        }
    };
    stdout
        .write_all(text.as_bytes())
        .map_err(|error| CliError::Io {
            action: "writing stdout".to_string(),
            error,
        })?;
    Ok(ExitCode::Success)
}

/// Every ordered pair of distinct formats that has a path, in id order.
fn all_plans() -> Vec<Plan> {
    let formats = registry::all_formats();
    let converters = registry::all_converters();
    let options = PlanOptions::default();
    let mut plans = Vec::new();
    for from in &formats {
        for to in &formats {
            if from.id == to.id {
                continue;
            }
            if let Ok(plan) = planner::plan(converters, from, to, &options) {
                plans.push(plan);
            }
        }
    }
    plans
}

fn path_names(plan: &Plan) -> String {
    let names: Vec<&str> = plan.hops.iter().map(|hop| hop.name()).collect();
    names.join(" -> ")
}

fn render_human() -> String {
    let mut text = String::new();
    for plan in all_plans() {
        let line = format!(
            "{} -> {}: {} via {}\n",
            plan.from().id,
            plan.to().id,
            plan.worst_fidelity().label(),
            path_names(&plan)
        );
        text.push_str(&line);
    }
    text
}

fn render_json() -> String {
    let mut buffer: Vec<u8> = Vec::new();
    {
        let mut writer = JsonWriter::new(&mut buffer);
        let _ = writer.begin_array();
        for plan in all_plans() {
            let _ = writer.begin_object();
            let _ = writer.key("from");
            let _ = writer.string(plan.from().id);
            let _ = writer.key("to");
            let _ = writer.string(plan.to().id);
            let _ = writer.key("fidelity");
            let _ = writer.string(plan.worst_fidelity().label());
            let _ = writer.key("hops");
            let _ = writer.begin_array();
            for hop in plan.describe() {
                let _ = write_hop(&mut writer, &hop);
            }
            let _ = writer.end_array();
            let _ = writer.end_object();
        }
        let _ = writer.end_array();
        let _ = writer.flush();
    }
    let mut text = String::from_utf8(buffer).unwrap_or_default();
    text.push('\n');
    text
}

pub fn render_markdown() -> String {
    let mut text = String::new();
    text.push_str("# Formats and Conversion Paths\n\n");
    text.push_str("Generated by `sublime paths --markdown`. Do not edit by hand. CI fails if this file is stale.\n\n");

    text.push_str("## Formats\n\n");
    text.push_str("| Category | Id | Name | Extensions | Produced by | Consumed by |\n");
    text.push_str("|---|---|---|---|---|---|\n");
    let mut formats = registry::all_formats();
    formats.sort_by(|left, right| (left.category, left.id).cmp(&(right.category, right.id)));
    for format in formats {
        let mut produced_by: Vec<&str> = Vec::new();
        let mut consumed_by: Vec<&str> = Vec::new();
        for converter in registry::all_converters() {
            if converter.to().id == format.id {
                produced_by.push(converter.name());
            }
            if converter.from().id == format.id {
                consumed_by.push(converter.name());
            }
        }
        let line = format!(
            "| {} | {} | {} | {} | {} | {} |\n",
            format.category.label(),
            format.id,
            format.display_name,
            format.extensions.join(", "),
            or_dash(&produced_by),
            or_dash(&consumed_by)
        );
        text.push_str(&line);
    }

    text.push_str("\n## Converters\n\n");
    text.push_str("| Name | From | To | Tier | Fidelity | Notes |\n");
    text.push_str("|---|---|---|---|---|---|\n");
    for converter in registry::all_converters() {
        let fidelity = converter.fidelity();
        let line = format!(
            "| {} | {} | {} | {} | {} | {} |\n",
            converter.name(),
            converter.from().id,
            converter.to().id,
            converter.tier().label(),
            fidelity.kind().label(),
            fidelity.description().unwrap_or("")
        );
        text.push_str(&line);
    }

    text.push_str("\n## Paths\n\n");
    text.push_str("| From | To | Fidelity | Path | Notes |\n");
    text.push_str("|---|---|---|---|---|\n");
    for plan in all_plans() {
        let notes = plan.loss_descriptions().join("; ");
        let line = format!(
            "| {} | {} | {} | {} | {} |\n",
            plan.from().id,
            plan.to().id,
            plan.worst_fidelity().label(),
            path_names(&plan),
            notes
        );
        text.push_str(&line);
    }

    text.push_str("\n## Map\n\n");
    text.push_str("One graph per category and one for the crossings between them. One arrow per converter: solid for lossless, labeled for conditional, dotted for lossy; longer paths chain them. A stadium-shaped format has a converter into another category.\n\n");
    text.push_str(&render_mermaid());
    text
}

/// The map at the bottom of DOCS/FORMATS.md: one Mermaid graph per
/// category with the converters inside it, and a last graph of the
/// converters that cross categories. A format with a converter into
/// another category is drawn as a stadium (`([id])`) in its own graph and
/// again in the crossing graph, where the other category is a hexagon
/// (`{{label}}`) standing for the hub behind it.
#[inline(never)]
fn render_mermaid() -> String {
    let mut formats = registry::all_formats();
    formats.sort_by(|left, right| (left.category, left.id).cmp(&(right.category, right.id)));
    let converters = registry::all_converters();
    let crosses = |id: &str| {
        converters.iter().any(|converter| {
            (converter.from().id == id || converter.to().id == id)
                && converter.from().category != converter.to().category
        })
    };
    let mut text = String::new();
    let mut categories: Vec<Category> = formats.iter().map(|format| format.category).collect();
    categories.dedup();
    for category in &categories {
        text.push_str("### ");
        text.push_str(category.label());
        text.push_str("\n\n```mermaid\ngraph LR\n");
        for format in formats.iter().filter(|format| format.category == *category) {
            text.push_str("  ");
            push_node(&mut text, format.id, crosses(format.id));
            text.push('\n');
        }
        for converter in converters {
            let same =
                converter.from().category == *category && converter.to().category == *category;
            if same {
                push_edge(
                    &mut text,
                    converter.from().id,
                    arrow_for(*converter),
                    converter.to().id,
                );
            }
        }
        text.push_str("```\n\n");
    }
    let crossing: Vec<&&dyn Converter> = converters
        .iter()
        .filter(|converter| converter.from().category != converter.to().category)
        .collect();
    if !crossing.is_empty() {
        text.push_str("### Between categories\n\n");
        text.push_str("A format's converter into another category opens every path that category already has, so the other side is drawn as the category itself.\n\n```mermaid\ngraph LR\n");
        let mut drawn: Vec<String> = Vec::new();
        for converter in crossing {
            let from = converter.from();
            let to = converter.to();
            let mut line = String::from("  ");
            if from.category < to.category {
                push_mermaid_id(&mut line, from.id);
                line.push_str(arrow_for(*converter));
                line.push_str(to.category.label());
                line.push_str("{{");
                line.push_str(to.category.label());
                line.push_str("}}");
            } else {
                line.push_str(from.category.label());
                line.push_str("{{");
                line.push_str(from.category.label());
                line.push_str("}}");
                line.push_str(arrow_for(*converter));
                push_mermaid_id(&mut line, to.id);
            }
            line.push('\n');
            if !drawn.contains(&line) {
                text.push_str(&line);
                drawn.push(line);
            }
        }
        text.push_str("```\n");
    }
    text
}

fn arrow_for(converter: &dyn Converter) -> &'static str {
    match converter.fidelity().kind() {
        FidelityKind::Lossless => " --> ",
        FidelityKind::Conditional => " -- conditional --> ",
        FidelityKind::Lossy => " -. lossy .-> ",
    }
}

/// A format node: a stadium when it has a converter across categories.
fn push_node(text: &mut String, format_id: &str, crosses: bool) {
    push_mermaid_id(text, format_id);
    text.push_str(if crosses { "([\"" } else { "[\"" });
    text.push_str(format_id);
    text.push_str(if crosses { "\"])" } else { "\"]" });
}

fn push_edge(text: &mut String, from: &str, arrow: &str, to: &str) {
    text.push_str("  ");
    push_mermaid_id(text, from);
    text.push_str(arrow);
    push_mermaid_id(text, to);
    text.push('\n');
}

/// Mermaid node ids cannot contain hyphens, which read as edge syntax.
fn push_mermaid_id(text: &mut String, format_id: &str) {
    for ch in format_id.chars() {
        if ch == '-' {
            text.push('_');
        } else {
            text.push(ch);
        }
    }
}

fn or_dash(names: &[&str]) -> String {
    if names.is_empty() {
        return "-".to_string();
    }
    names.join(", ")
}
